defaultPlacement: end
fieldLayouts:
  fd862cd4-8bfd-484d-903d-b3970ee961ca:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 1a8de00d-d627-41a2-a7ee-189506d488e3
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 50eaea3a-abb6-4aeb-96ce-343278fcdb3a
        userCondition: null
handle: categories
name: 'Feest categorieën'
siteSettings:
  0a16d5ba-6082-499e-8075-2a7617fc17ab: # datamanegement_opdracht_2
    hasUrls: true
    template: party/index.twig
    uriFormat: 'party/cat/{slug}'
structure:
  maxLevels: 3
  uid: 0db374e1-c02c-4e67-a49e-ffe01a098114
