fieldLayouts:
  855108f9-118b-4741-9e69-9e5d3cf270c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 2b9006d2-d346-41f9-ab29-cf5d1489b3fa
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: d3d725e4-86f6-4073-8c37-231fa8ba1050
        userCondition: null
fs: uploads
handle: images
name: images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
