defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  0a16d5ba-6082-499e-8075-2a7617fc17ab: # datamanegement_opdracht_2
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
